name: idb
description: iDB
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    flutter_keyboard_visibility: ^5.0.1
    flutter_mobx: ^2.0.0
    flutter_svg: ^0.22.0
    get_it: ^7.2.0
    path: ^1.8.0
    path_provider: ^2.0.1
    sentry: ^5.0.0
    uuid: ^3.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    build_runner: ^2.0.1
    json_serializable: ^4.1.1
    build_test: ^2.1.0
    mobx_codegen: ^2.0.1+3
    shared_preferences: ^2.0.5

flutter:
    uses-material-design: true
