name: idb
description: iDB
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    desktop_window: ^0.4.0
    flutter_keyboard_visibility: ^5.0.1
    flutter_mobx: ^2.0.0
    flutter_svg: ^0.22.0
    flutter_html: ^2.1.1
    get_it: ^7.2.0
    html: ^0.15.0
    path: ^1.8.0
    path_provider: ^2.0.1
    sentry: ^5.0.0
    uuid: ^3.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    build_runner: ^2.0.1
    json_serializable: ^4.1.1
    build_test: ^2.1.0
    mobx_codegen: ^2.0.1+3
    shared_preferences: ^2.0.5

flutter:
    uses-material-design: true

    fonts:
        - family: Inconsolata
          fonts:
              - asset: assets/fonts/Inconsolata-Bold.ttf
                weight: 700
              - asset: assets/fonts/Inconsolata-Regular.ttf
                weight: 400

    assets:
        - assets/images/
        - assets/images/pics/
        - assets/images/svg/
