name: idb
description: iDB
publish_to: 'none'
version: 1.0.1

environment:
    sdk: '>=2.14.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    clipboard: ^0.1.3
    cupertino_icons: ^1.0.3
    desktop_window: ^0.4.0
    file_picker: ^4.0.2
    flutter_keyboard_visibility: ^5.0.3
    flutter_mobx: ^2.0.2
    flutter_svg: ^0.22.0
    flutter_html: ^2.1.1
    get_it: ^7.2.0
    html: ^0.15.0
    mime: ^1.0.0
    package_info_plus: ^1.0.6
    path: ^1.8.0
    path_provider: ^2.0.3
    sentry_flutter: ^6.0.0
    shared_preferences: ^2.0.7
    url_launcher: ^6.0.10
    uuid: ^3.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    build_runner: ^2.1.2
    json_serializable: ^5.0.0
    build_test: ^2.1.3
    mobx_codegen: ^2.0.3

flutter:
    uses-material-design: true

    fonts:
        - family: Inconsolata
          fonts:
              - asset: assets/fonts/Inconsolata-Bold.ttf
                weight: 700
              - asset: assets/fonts/Inconsolata-Regular.ttf
                weight: 400

    assets:
        - assets/images/
        - assets/images/pics/
        - assets/images/svg/
        - assets/json/
